<a href="https://colab.research.google.com/github/jerussi123/Proyecto_tec_andes/blob/main/Soporte_1_Fuentes_de_Limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Limpieza y Alistamiento de Datos

Carlos Pérez A01029313

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
file_path = 'productividad.csv'
df = pd.read_csv(file_path, sep=';', header=0)

In [3]:
df.head()

date   quarter  department       day  team  targeted_productivity  \
0  1/01/2015  Quarter1      sweing  Thursday     8                   0.80   
1  1/01/2015  Quarter1  finishing   Thursday     1                   0.75   
2  1/01/2015  Quarter1      sweing  Thursday    11                   0.80   
3  1/01/2015  Quarter1      sweing  Thursday    12                   0.80   
4  1/01/2015  Quarter1      sweing  Thursday     6                   0.80   

     smv     wip  over_time  incentive  idle_time  idle_men  \
0  26.16  1108.0       7080         98        0.0         0   
1   3.94     NaN        960          0        0.0         0   
2  11.41   968.0       3660         50        0.0         0   
3  11.41   968.0       3660         50        0.0         0   
4  25.90  1170.0       1920         50        0.0         0   

   no_of_style_change  no_of_workers actual_productivity  
0                   0           59.0         0.940725424  
1                   0            8.0              0.8865  
2                   0           30.5         0.800570492  
3                   0           30.5         0.800570492  
4                   0           56.0         0.800381944

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1197 non-null   object 
 1   quarter                1197 non-null   object 
 2   department             1197 non-null   object 
 3   day                    1197 non-null   object 
 4   team                   1197 non-null   int64  
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64  
 9   incentive              1197 non-null   int64  
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64  
 12  no_of_style_change     1197 non-null   int64  
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   object 
dtypes: f

In [5]:
df = df.drop(["no_of_style_change"], axis=1, errors='ignore')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1197 non-null   object 
 1   quarter                1197 non-null   object 
 2   department             1197 non-null   object 
 3   day                    1197 non-null   object 
 4   team                   1197 non-null   int64  
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64  
 9   incentive              1197 non-null   int64  
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64  
 12  no_of_workers          1197 non-null   float64
 13  actual_productivity    1197 non-null   object 
dtypes: float64(5), int64(4), object(5)
memory usage: 131.0+ 

In [7]:
df.isnull().sum( )

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_workers              0
actual_productivity        0
dtype: int64

In [8]:
df['wip'].fillna(0, inplace=True)

<ipython-input-8-96a2d9319b0c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['wip'].fillna(0, inplace=True)


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1197 non-null   object 
 1   quarter                1197 non-null   object 
 2   department             1197 non-null   object 
 3   day                    1197 non-null   object 
 4   team                   1197 non-null   int64  
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    1197 non-null   float64
 8   over_time              1197 non-null   int64  
 9   incentive              1197 non-null   int64  
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64  
 12  no_of_workers          1197 non-null   float64
 13  actual_productivity    1197 non-null   object 
dtypes: float64(5), int64(4), object(5)
memory usage: 131.0+ 

In [10]:
df.duplicated().sum()

0

In [11]:
df['no_of_workers'] = df['no_of_workers'].astype('int64')

In [12]:
df['team'] = df['team'].astype('object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1197 non-null   object 
 1   quarter                1197 non-null   object 
 2   department             1197 non-null   object 
 3   day                    1197 non-null   object 
 4   team                   1197 non-null   object 
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    1197 non-null   float64
 8   over_time              1197 non-null   int64  
 9   incentive              1197 non-null   int64  
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64  
 12  no_of_workers          1197 non-null   int64  
 13  actual_productivity    1197 non-null   object 
dtypes: float64(4), int64(4), object(6)
memory usage: 131.0+ 

In [14]:
def corregir_float(valor):
    str_valor = str(valor)
    if str_valor.count('.') > 1:
        # Si hay más de un punto, eliminar el primero
        partes = str_valor.split('.')
        return float(partes[0] + '.' + ''.join(partes[1:]))
    return float(str_valor)

df['actual_productivity'] = df['actual_productivity'].apply(corregir_float)

In [15]:
df['actual_productivity'] = pd.to_numeric(df['actual_productivity'], errors='coerce')

In [16]:
df['actual_productivity'].describe()

count    1197.000000
mean        0.837986
std         3.046194
min         0.233705
25%         0.650307
50%         0.773333
75%         0.850253
max       105.028058
Name: actual_productivity, dtype: float64

In [17]:
over_1 = df[df['actual_productivity'] >= 1].index
df = df.drop(over_1)

In [18]:
df['actual_productivity'].describe()

count    1160.000000
mean        0.725991
std         0.169404
min         0.233705
25%         0.650061
50%         0.754425
75%         0.845167
max         0.999995
Name: actual_productivity, dtype: float64

In [19]:
df['incentive'].unique()

array([  98,    0,   50,   38,   45,   34,   44,   63,   56,   40,   60,
         26,   75,   23,   35,   69,   88,   30,   54,   37,   70,   27,
         21,   24,   94,   29,   81,   55,   46,  100,   53,   93,   49,
         90,  113,   33,   32,   62,   65,  960, 1080, 2880, 3600, 1440,
       1200,   25])

In [20]:
df['incentive'].describe()

count    1160.000000
mean       37.012931
std       162.300882
min         0.000000
25%         0.000000
50%         0.000000
75%        50.000000
max      3600.000000
Name: incentive, dtype: float64

In [21]:
over_500 = df[df['incentive'] >= 500].index
df = df.drop(over_500)
df['incentive'].describe()

count    1150.000000
mean       24.291304
std        27.957126
min         0.000000
25%         0.000000
50%         0.000000
75%        50.000000
max       113.000000
Name: incentive, dtype: float64

In [22]:
df['idle_time'].unique()

array([  0. ,  90. , 150. , 270. , 300. ,   2. ,   5. ,   8. ,   4.5,
         3.5,   4. ,   6.5])

In [23]:
df['idle_time'].describe()

count    1150.000000
mean        0.760000
std        12.966223
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       300.000000
Name: idle_time, dtype: float64

In [24]:
over_50 = df[df['idle_time'] >= 50].index
df = df.drop(over_50)
df['idle_time'].describe()

count    1146.000000
mean        0.055846
std         0.540035
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         8.000000
Name: idle_time, dtype: float64

In [25]:
df['wip'].describe()

count     1146.000000
mean       672.443281
std       1465.236757
min          0.000000
25%          0.000000
50%        583.000000
75%       1073.000000
max      23122.000000
Name: wip, dtype: float64

In [26]:
over_3000 = df[df['wip'] >= 3000].index
df = df.drop(over_3000)
df['wip'].describe()

count    1139.000000
mean      572.661984
std       568.400191
min         0.000000
25%         0.000000
50%       573.000000
75%      1069.000000
max      2984.000000
Name: wip, dtype: float64

In [27]:
df['over_time'].unique()

array([ 7080,   960,  3660,  1920,  6720,  6900,  6000,  6480,  2160,
        7200,  1440,  6600,  5640,  1560,  6300,  6540, 13800,  6975,
        7020,  6780,  4260,  6660,  4320,  6960,  2400,  3840,  4800,
        4440,  1800,  2700, 10620, 10350,  9900,  5310, 10170,  4470,
       10530, 10440,  5490,  5670,  9720, 12600, 10050, 15120, 14640,
         900, 25920, 10260,  2760,  4710,  9540,  7680,  3600,  6420,
        7980,  3240,  8220,  6930,  8460,  7350,  5400,  1620,  1980,
        2970,  7320,  5100,  3390,  1260,  3420,  8970,  4950, 10080,
        9810,  6570,  5040,  4380,  3630,  8280,  6120,  5580,  3720,
        5760,  7470, 10500,  6360,  4140,  8400, 12180,  9000, 15000,
       10770, 12000,  9360,  3060,  2520,   720,  3780, 10320,   360,
        1080,  1200,  4080,   240,  5880,  6240,  6840,  4200,  3960,
         600,  2280,  1320,  5460,  2040,  4020,  3000,  3360,  2640,
        7500,  2880,   120,  3300,     0,  3480,  7380,  4560,  5940,
        7140,  5160,

In [28]:
df['over_time'].describe()

count     1139.000000
mean      4598.867428
std       3361.542425
min          0.000000
25%       1440.000000
50%       3960.000000
75%       6960.000000
max      25920.000000
Name: over_time, dtype: float64

In [31]:
over_25000 = df[df['over_time'] >= 25000].index
df = df.drop(over_25000)
df['over_time'].describe()

count     1138.000000
mean      4580.131810
std       3302.989349
min          0.000000
25%       1440.000000
50%       3960.000000
75%       6960.000000
max      15120.000000
Name: over_time, dtype: float64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1138 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1138 non-null   object 
 1   quarter                1138 non-null   object 
 2   department             1138 non-null   object 
 3   day                    1138 non-null   object 
 4   team                   1138 non-null   object 
 5   targeted_productivity  1138 non-null   float64
 6   smv                    1138 non-null   float64
 7   wip                    1138 non-null   float64
 8   over_time              1138 non-null   int64  
 9   incentive              1138 non-null   int64  
 10  idle_time              1138 non-null   float64
 11  idle_men               1138 non-null   int64  
 12  no_of_workers          1138 non-null   int64  
 13  actual_productivity    1138 non-null   float64
dtypes: float64(5), int64(4), object(5)
memory usage: 133.4+ KB


In [33]:
df['date'] = pd.to_datetime(df['date'])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1138 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   date                   1138 non-null   datetime64[ns]
 1   quarter                1138 non-null   object        
 2   department             1138 non-null   object        
 3   day                    1138 non-null   object        
 4   team                   1138 non-null   object        
 5   targeted_productivity  1138 non-null   float64       
 6   smv                    1138 non-null   float64       
 7   wip                    1138 non-null   float64       
 8   over_time              1138 non-null   int64         
 9   incentive              1138 non-null   int64         
 10  idle_time              1138 non-null   float64       
 11  idle_men               1138 non-null   int64         
 12  no_of_workers          1138 non-null   int64         
 13  actual_p

In [35]:
df['department'].unique()

array(['sweing', 'finishing ', 'finishing'], dtype=object)

In [36]:
df['department'].value_counts()

department
sweing        654
finishing     253
finishing     231
Name: count, dtype: int64

In [37]:
df['department'] = df['department'].replace('finishing ','finishing')
df['department'].value_counts()

department
sweing       654
finishing    484
Name: count, dtype: int64

In [38]:
df['quarter'].unique()

array(['Quarter1', 'Quarter2', 'Quarter3', 'Quarter4', 'Quarter5'],
      dtype=object)

In [39]:
df['team'].unique()

array([8, 1, 11, 12, 6, 7, 2, 3, 9, 10, 5, 4], dtype=object)

In [40]:
df['day'].unique()

array(['Thursday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday'],
      dtype=object)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1138 entries, 0 to 1196
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   date                   1138 non-null   datetime64[ns]
 1   quarter                1138 non-null   object        
 2   department             1138 non-null   object        
 3   day                    1138 non-null   object        
 4   team                   1138 non-null   object        
 5   targeted_productivity  1138 non-null   float64       
 6   smv                    1138 non-null   float64       
 7   wip                    1138 non-null   float64       
 8   over_time              1138 non-null   int64         
 9   incentive              1138 non-null   int64         
 10  idle_time              1138 non-null   float64       
 11  idle_men               1138 non-null   int64         
 12  no_of_workers          1138 non-null   int64         
 13  actual_p

In [ ]:
df.to_excel("productividad_limpia.xlsx", index=False)